services:
  odoo:
    image: odoo:13
    container_name: odoo
    ports:
      - "80:8069"
    env_file: .env
    volumes:
      - ./odoo:/etc/odoo
      - ./addons:/addons
      - ./odoo-data:/var/lib/odoo
    links:
      - db:db  # This creates a link with hostname 'db'

  db:
    image: postgres:15
    container_name: db
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - default
    restart: unless-stopped
